# -*- coding: utf-8 -*-
"""
Django settings for django_miprimeraplicacion project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#nnp73be@=^maya94d3eu8w%)=bff^my@ak%(197$1#9dx87ox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
                  
    'django.contrib.admin',
    'django.contrib.admindocs',
    #'django.contrib.auth',
    #'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'preguntasyrespuestas',
    
    # Usuarios y grupos
    'django.contrib.auth',
    'django.contrib.contenttypes',
    
    #===========================================
    # django-cas CONFIGURATION  
    #===========================================
    # https://bitbucket.org/cpcc/django-cas/
    #===========================================
    'django_cas',
   
   # MIS APPS
    'accounts',
]


MIDDLEWARE_CLASSES = [
    # Usuarios y grupos
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
   
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #===========================================
    # django-cas CONFIGURATION  
    #===========================================
    # https://bitbucket.org/cpcc/django-cas/
    #===========================================
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_cas.middleware.CASMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
]

#===========================================
# django-cas CONFIGURATION  
#===========================================
# https://bitbucket.org/cpcc/django-cas/
#===========================================
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_cas.backends.CASBackend',

)


ROOT_URLCONF = 'django_gedea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["/home/dru/workspace/gedea/src/miprimeraplicacion_django/static"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_gedea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))


# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    'web/css/',
    'web/img/',
    '/web/js/',
]

#===========================================
# django-cas CONFIGURATION  
#===========================================
# https://bitbucket.org/cpcc/django-cas/
#===========================================
CAS_SERVER_URL='http://login.ull.es/cas-1/'
CAS_VERSION='CAS_2_SAML_1_0'

#Ficheros est�ticos
STATIC_URL = '/static/'
STATIC_ROOT = ''

# LOGIN
# Redirect when login is correct.
#LOGIN_REDIRECT_URL = "/my/"

# tutorial_django/settings.py
LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'

#site
SITE_ID = 1